"""empty message

Revision ID: 4e7a4e56f759
Revises: b9580ae0b726
Create Date: 2017-03-09 08:53:30.648000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e7a4e56f759'
down_revision = 'b9580ae0b726'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('biography', sa.String(length=200), nullable=True))
    op.drop_column('user_profile', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('user_profile', 'biography')
    # ### end Alembic commands ###
