"""empty message

Revision ID: 69ff9dedc9d8
Revises: 4e7a4e56f759
Create Date: 2017-03-09 10:02:00.529000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '69ff9dedc9d8'
down_revision = '4e7a4e56f759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'profile_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('profile_image', postgresql.BYTEA(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
