"""empty message

Revision ID: 9ec328e46405
Revises: e246b81b633a
Create Date: 2017-03-09 19:26:34.373000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ec328e46405'
down_revision = 'e246b81b633a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'profile_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('profile_image', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
