"""empty message

Revision ID: e246b81b633a
Revises: 69ff9dedc9d8
Create Date: 2017-03-09 10:02:17.755000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e246b81b633a'
down_revision = '69ff9dedc9d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('profile_image', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'profile_image')
    # ### end Alembic commands ###
